name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
      - run: npm i -g yarn
      - run: yarn set version berry
      - run: cat .yarnrc_patch.yml >> .yarnrc.yml
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v2.1.4
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-
      - run: yarn install
      - run: yarn clean
      - run: yarn compile
      - run: yarn build
      - run: yarn lint
      - run: yarn test:coverage
      - run: yarn docs
      - run: yarn cy:compile
      - uses: cypress-io/github-action@v2
        # with:
          # start: npm run serve
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      # - run: |
      #     mkdir -p public/main
      #     cp -r build/* public/main
      #     mv README.md public/
      #     mkdir -p public_dev/develop
      #     cp -r build/* public_dev/develop

      # - name: Deploy Main
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   uses: upsetjs/actions-gh-pages@sgratzl
      #   env:
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      #   with:
      #     personal_token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
      #     external_repository: lineupjs/lineup.js.org
      #     publish_branch: main
      #     publish_dir: ./public
      #     enable_jekyll: true
      #     remove_path_spec: 'README.md,main'

      # - name: Deploy Develop
      #   if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      #   uses: upsetjs/actions-gh-pages@sgratzl
      #   env:
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      #   with:
      #     personal_token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
      #     external_repository: lineupjs/lineup.js.org
      #     publish_branch: main
      #     publish_dir: ./public_dev
      #     enable_jekyll: true
      #     remove_path_spec: 'develop'
